services:
  - type: web
    name: ecomm-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false

      - key: JWT_SECRET
        value: 6f5f5a25-bb9f-4b68-a38d-41c23d112bd4
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://e-comm-mean-stack.vercel.app,https://s-a-a-r-v-i.vercel.app,https://e-comm-mean-stack-42og.onrender.com
      - key: FRONTEND_URL
        value: https://s-a-a-r-v-i.vercel.app
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
    healthCheckPath: /health
